In [4]:
pip install numpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.1/115.1 kB 1.9 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.0/14.0 MB 9.0 MB/s eta 0:00:0000:0100:01

[notice] A new release of pip is available: 23.3.1 -> 23.3.2
[notice] To update, run: python3.11 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np

In [7]:
# create a 3 * 4 array of element 4
a = np.full((3, 4), 4)
a

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

In [16]:
a = np.diag([1, 2, 3, 4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [18]:
b = np.arange(1, 100, 1)
b
b[[4,5,6]]

array([5, 6, 7])

In [29]:
c =np.array([[1,2,3],[4,5,6]])
c[0,1]


array([4])

In [31]:
# greater than 3
c[c>3]

array([4, 5, 6])

In [33]:
 #greter than 3 and less than 5
c[(c>3) & (c<5)]

array([4])

In [36]:
d = np.array([1,2,3,4,5,6,7,8,9,10])
d[1] = 13
d

array([ 1, 13,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
e = d
e[1] =2
e

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
arr2 = d.copy()
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
# To check if two arrays share the same memory block or not 
np.shares_memory(arr2,d)

False

In [44]:
np.shares_memory(d,e)


True

In [48]:
arr3 = np.random.random((4,5))
arr3

array([[0.76915121, 0.99707605, 0.58696692, 0.42785057, 0.83783371],
       [0.81790982, 0.626128  , 0.97782081, 0.44163083, 0.17762858],
       [0.68501374, 0.08633952, 0.40968864, 0.45124406, 0.42232557],
       [0.84016119, 0.79544199, 0.09896354, 0.98002846, 0.57235585]])

In [121]:

np.random.seed(0) # seed fixed the random number generation
arr4 = np.random.random((3,4))
arr4

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492]])

In [126]:
arr5 = np.random.randint(0,10, size=(3,4))
arr5

array([[4, 9, 6, 5],
       [7, 8, 8, 9],
       [2, 8, 6, 6]])

In [149]:
# how to round off the values
arr6=np.round(arr4, 2)
arr6=arr6*100
arr6=arr6.astype(int)
arr6


array([[55, 72, 60, 54],
       [42, 65, 44, 89],
       [96, 38, 79, 53]])

In [150]:
arr6.shape

(3, 4)

In [156]:
arr6=arr6.reshape(2,6)
arr6

array([[55, 72, 60, 54, 42, 65],
       [44, 89, 96, 38, 79, 53]])

In [160]:
# exponential 
np.exp(arr6)   

array([[7.69478527e+23, 1.85867175e+31, 1.14200739e+26, 2.83075330e+23,
        1.73927494e+18, 1.69488924e+28],
       [1.28516001e+19, 4.48961282e+38, 4.92345829e+41, 3.18559318e+16,
        2.03828107e+34, 1.04137594e+23]])

In [161]:
arr7 = arr6.T
arr7

array([[55, 44],
       [72, 89],
       [60, 96],
       [54, 38],
       [42, 79],
       [65, 53]])

In [162]:
arr7.max()

96

In [163]:
np.dot(arr6,arr7)

array([[20714, 23403],
       [23403, 29567]])