In [1]:
print("hello pandas")

hello pandas


In [4]:
a = 1
for i in range(0,10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [10]:
import pandas as pd
import numpy as np

In [13]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [14]:
series_data = pd.Series(arr)
print(series_data)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [15]:
type(series_data)

pandas.core.series.Series

In [19]:
x = pd.Series(arr,index=[100,101,102,103,104])
print(x)

100    1
101    2
102    3
103    4
104    5
dtype: int64


In [20]:
data = {'a': 1, 'b': 2, 'c': 3 ,'d': 4}
x = pd.Series(data)
print(x)

a    1
b    2
c    3
d    4
dtype: int64


In [21]:
x = pd.Series(5, index=[0,1,2,3,4,5,6,7,8])
x


0    5
1    5
2    5
3    5
4    5
5    5
6    5
7    5
8    5
dtype: int64

In [29]:
data = [1,2,3,4,5]
x= pd.Series(data,index=[90,91,92,93,94])
x

90    1
91    2
92    3
93    4
94    5
dtype: int64

In [47]:
x[92]

3

In [48]:
x[[90,91,92]]

90    1
91    2
92    3
dtype: int64

In [49]:
#DataFrame
import pandas as pd
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []


In [53]:
name = ['dheeraj','yash','naresh','himanshu','aryan','ajlal']
age =[19,19,21,21,18,20]
data = {'Name':name ,'Age':age}
df = pd.DataFrame(data)
df

Name  Age
0   dheeraj   19
1      yash   19
2    naresh   21
3  himanshu   21
4     aryan   18
5     ajlal   20

In [6]:
import pandas as pd
import numpy as np

In [13]:
data = np.array([10,15,5,60,79,90,89,90,95,100,67,29,78])
df= pd.DataFrame(data=data,index=[0,1,2,3,4,5,6,7,8,9,10,11,12],columns=['marks'])
print(df[df['marks']>60])


    marks
4      79
5      90
6      89
7      90
8      95
9     100
10     67
12     78


In [9]:
import pandas as pd
data = {
    'Age':[1,10,14,50,8,43,34,7,1,23]
}
df = pd.DataFrame(data)
df[df['Age']<30]
df['Name']=['Dheeraj','Aryan','Ajlal','Yash','Shashank','Anuja','Tanya','Abhishek','Nikita','Mansi']
df=df['Age'].unique()
print(df)



[ 1 10 14 50  8 43 34  7 23]


In [1]:
import pandas as pd
import numpy as np

In [2]:
newarr = np.arange(1,101)
s1 = pd.Series(newarr)
s1[1:4]

1    2
2    3
3    4
dtype: int64

In [3]:
# last 5 elements
s1[-5:]

95     96
96     97
97     98
98     99
99    100
dtype: int64

In [4]:
s1[[9,19,24]]

9     10
19    20
24    25
dtype: int64

In [5]:
s1.values

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [8]:
Name = ['Dheeraj','Aryan','Ajlal','Yash','Shashank']
Age = [19,19,20,19,21]
data = {'Name':Name,'Age':Age}
df = pd.DataFrame(data,index=[1,2,3,4,5])
df


Name  Age
1   Dheeraj   19
2     Aryan   19
3     Ajlal   20
4      Yash   19
5  Shashank   21

In [22]:
df["Roll No"] = [11,13,56,8,3]
df['city'] = ['Mathura','Firozabad','Bhasti','Mathura','Mathura']
df['Blood-group'] = ['AB+','B+','O+','B+','B+']
df

Name  Age  Roll No       city Blood-group
1   Dheeraj   19       11    Mathura         AB+
2     Aryan   19       13  Firozabad          B+
3     Ajlal   20       56     Bhasti          O+
4      Yash   19        8    Mathura          B+
5  Shashank   21        3    Mathura          B+

In [23]:
df.drop('Blood-group',axis=1,inplace=True)
df

Name  Age  Roll No       city
1   Dheeraj   19       11    Mathura
2     Aryan   19       13  Firozabad
3     Ajlal   20       56     Bhasti
4      Yash   19        8    Mathura
5  Shashank   21        3    Mathura

In [24]:
df.pop('city')
df


Name  Age  Roll No
1   Dheeraj   19       11
2     Aryan   19       13
3     Ajlal   20       56
4      Yash   19        8
5  Shashank   21        3

In [32]:
df.shape


(5, 3)